name: Pull Request Checks

on:
  pull_request:
    branches: ["main"]

  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs: 
  pull-request-checks:
    name: Pull Request Checks
    uses: GIS-Workshop-LLC/reusable-workflows/.github/workflows/pull-request.yaml@main
    secrets:
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
